name: Publish Docker image
on:
  push:
    branches:
    - main
  workflow_dispatch:
  schedule:
    - cron: "12 12 * * *"

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      # - id: agent
      #   uses: pozetroninc/github-action-get-latest-release@v0.5.0
      #   with:
      #     repository: microsoft/azure-pipelines-agent

      # - name: Parse semver string
      #   id: semver_parser
      #   uses: booxmedialtd/ws-action-parse-semver@v1
      #   with:
      #     input_string: ${{ steps.agent.outputs.release }}

      # See https://github.com/marketplace/actions/fetch-latest-release
      - id: agent
        uses: thebritican/fetch-latest-release@v2.0.0
        with:
          repo_path: microsoft/azure-pipelines-agent
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Parse semver string
        id: semver_parser
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ steps.agent.outputs.tag_name }}

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1
      
      # See https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/nobitagamer/azure-pipelines-agent:${{ steps.semver_parser.outputs.fullversion }}
            ghcr.io/nobitagamer/azure-pipelines-agent:latest
          context: ./docker
          file: ./docker/release.dockerfile
          build-args: AGENT_VERSION=${{ steps.semver_parser.outputs.fullversion }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          # cache-from: type=registry,ref=ghcr.io/nobitagamer/azure-pipelines-agent:latest
          # cache-to: type=inline

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
